# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
---
- name: Download Intel SGX DCAP Driver
  get_url:
    url: https://downloadcenter.intel.com/downloads/eula/28154/Intel-Software-Guard-Extensions-Intel-SGX-Driver-for-Windows-?httpDown=https%3A%2F%2Fdownloadmirror.intel.com%2F28154%2Feng%2Fintel_sgx_win_2.1.100..46245_PV.zip
    dest: "C:/tmp"

- name: Install the Intel SGX DCAP Driver
  command: /tmp/sgx_linux_x64_driver_dcap_36594a7.bin

- name: Remove the Intel SGX DCAP Driver installer
  file: path=/tmp/sgx_linux_x64_driver_dcap_36594a7.bin state=absent
