# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
---
- name: Download Intel SGX DCAP Driver
  get_url:
    url: https://downloadcenter.intel.com/downloads/eula/28154/Intel-Software-Guard-Extensions-Intel-SGX-Driver-for-Windows-?httpDown=https%3A%2F%2Fdownloadmirror.intel.com%2F28154%2Feng%2Fintel_sgx_win_2.1.100..46245_PV.zip
    dest: %USERPROFILE%\AppData\Local\{{SGX-version}}

- name: Install the Intel SGX DCAP Driver
  win_shell:  %USERPROFILE%\AppData\Local\{{SGX-version}}\Intel(R)_SGX_Windows_SDK_{{SGX-version}}.exe --a install 

- name: Remove the Intel SGX DCAP Driver installer
  win_file:
    path: %USERPROFILE%\AppData\Local\{{SGX-version}}
    state: absent
